/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_thebends_synth_SynthJni */

#ifndef _Included_org_thebends_synth_SynthJni
#define _Included_org_thebends_synth_SynthJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_thebends_synth_SynthJni
 * Method:    getSamples
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_thebends_synth_SynthJni_getSamples
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
